### ISSUE TITLE
ALU

### ISSUE THREAD

**Issue by chances190** [Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE#5]
**Instruções da ALU**
- [x] `ADD` 
- [ ] `ADDI`
- [ ] `SUB` 
- [x] `AND` 
- [ ] `OR`  
- [ ] `XOR` 
- [ ] `SLLI`
- [ ] `SRLI`
- [ ] `SRAI`
- [ ] `SLT` 
- [ ] `SLTI`
- [x] `BEQ` 
- [ ] `BNE` 
- [ ] `BLT` 
- [ ] `BGE`

**Comment by chances190** [comment]
![Operações da ALU](https://github.com/Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE/assets/69327389/290fa662-a704-4b30-b961-77d6f4c1fd1a)

**Comment by Mlcarvalho1** [comment]
Esta issue foi juntada com a da ALU controller.
