### ISSUE TITLE
ALU & ALU Controller

### ISSUE THREAD

**Issue by chances190** [Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE#6]
- [x] `ADD` 
- [x] `ADDI`
- [x] `SUB` 
- [x] `AND` 
- [x] `OR`  
- [x] `XOR` 
- [x] `SLLI`
- [x] `SRLI`
- [x] `SRAI`
- [x] `SLT` 
- [x] `SLTI`
- [x] `BEQ` 
- [x] `BNE` 
- [x] `BLT` 
- [x] `BGE`

**Comment by Mlcarvalho1** [comment]
pr https://github.com/Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE/pull/8

**Comment by Mlcarvalho1** [comment]
**Instruções da ALU**
- [x] `ADD` 
- [ ] `ADDI`
- [x] `SUB` 
- [x] `AND` 
- [ ] `OR`  
- [ ] `XOR` 
- [ ] `SLLI`
- [ ] `SRLI`
- [ ] `SRAI`
- [ ] `SLT` 
- [ ] `SLTI`
- [x] `BEQ` 
- [x] `BNE` 
- [ ] `BLT` 
- [ ] `BGE`

**Comment by Mlcarvalho1** [comment]
![image](https://github.com/Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE/assets/103081588/1b6851f9-46ac-4200-9f13-5f2b78a35dc5)

**Comment by chances190** [comment]
@Mlcarvalho1 Em alguns testes o `SW` não estava funcionando. Não sei qual o problema, mas é bom testar pra confirmar. Tirei o "testado" dela até alguém conferir.

**Comment by chances190** [comment]
Resolvido e testado. Vou dar Merge.
