### ISSUE TITLE
Mover a Branch Unit para a etapa ID

### ISSUE THREAD

**Issue by chances190** [Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE#9]
![](https://github.com/Mlcarvalho1/Projeto_IH_RISC_V_PIPELINE/assets/69327389/f259c4d8-8583-4e4d-93bf-6d3a04e24619)

**Comment by chances190** [comment]
**É preciso lógica adicional na Fowarding Unit e Hazard Detection Unit**

>The branch test to the ID stage implies additional forwarding and hazard detection
hardware, since a branch dependent on a result still in the pipeline must still work
properly with this optimization. For example, to implement branch if equal (and
its inverse), we will need to forward results to the equality test logic that operates
during ID. There are two complicating factors:
>1. During ID, we must decode the instruction, decide whether a bypass to
the equality test unit is needed, and complete the equality test so that if
the instruction is a branch, we can set the PC to the branch target address.
Forwarding for the operand of branches was formerly handled by the
ALU forwarding logic, but the introduction of the equality test unit in ID
will require new forwarding logic. Note that the bypassed source operands
of a branch can come from either the EX/MEM or MEM/WB pipeline registers.
>2. Because the value in a branch comparison is needed during ID but may be
produced later in time, it is possible that a data hazard can occur and a stall
will be needed. For example, if an ALU instruction immediately preceding
a branch produces the operand for the test in the conditional branch, a stall
will be required, since the EX stage for the ALU instruction will occur after
the ID cycle of the branch. By extension, if a load is immediately followed by
a conditional branch that depends on the load result, two stall cycles will be
needed, as the result from the load appears at the end of the MEM cycle but
is needed at the beginning of ID for the branch.

**Comment by Nether190** [comment]
Muito trabalhoso, não vale a pena.

**Comment by chances190** [comment]
Muito trabalhoso, não vale a pena.
